language: java
jdk: openjdk8
before_install:
- chmod +x mvnw
- npm install -g standard

services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - DB_NAME=runon_test
    - DB_USER=runon
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"

install:
  - npm install


deploy:
  provider: heroku
  api_key:
    secure: "e593bdec-c2ec-44cd-853f-6c6c17d24a02"
  app: ikantpostgis